@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}




@userNameForTesting = Luiz
@userEmailForTesting = luiz@email.com
@userPasswordForTesting = Ma@#123456
@userNewPasswordForTesting = M@#123456
@userPhoneNumber= 41952150693

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
}

# USER ########################################################################

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "{{userNameForTesting}}",
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}",
  "phoneNumber":"{{userPhoneNumber}}"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "{{userNameForTesting}}",
  "email": "{{userEmailForTesting}}"
}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "{{userPasswordForTesting}}",
  "newPassword": "{{userNewPasswordForTesting}}"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Read all user
# @name readAllUser
GET {{baseUrl}}/user/all
Authorization: Bearer {{jwtToken}}



### Delete one user
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

#PET
#######################################################################
###Get all Pets
# @name getAllPets
GET {{baseUrl}}/pet/
Authorization: Bearer {{jwtToken}}

###Create Pet
# @name createPet
POST {{baseUrl}}/pet
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name":"Mag",
  "race":"Labrador",
  "species":"dog",
  "birthDate": "2008-05-22"
  //,"erro":"rouba back"
}


